see #21515: NoSuchMethodError: 'void org.openstreetmap.josm.gui.widgets.HistoryComboBox.setPossibleItems(java.util.Collection)' - update code to recent changes in core, bump version - also seems to fix #18897
git-svn-id: https://josm.openstreetmap.de/osmsvn/applications/editors/josm/plugins@35856 b9d5c4c9-76e1-0310-9c85-f3177eceb1e4